{% set name = "modin" %}
{% set version = "0.10.2" %}

package:
  name: modin
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2feaf96a03423ab6ac012dd9e56fa29fb4c14ed858973f81f15b8fa1f701f717

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  # noarch disabled because the recipe now has selector for Ray, see below
  # noarch: python
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pandas ==1.3.2
    - dask >=2.22
    # - pyarrow 1.0
    # - spreadsheet >=0.1.0
    - distributed >=2.22
    # there is no Ray in conda-forge for MacOS yet, see https://github.com/conda-forge/ray-packages-feedstock/issues/2
    - ray-core >=1.4  # [win64 or linux64]

test:
  imports:
    - modin
    - modin.pandas
about:
  home: https://github.com/modin-project/modin
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Speed up your Pandas workflows by changing a single line of code
  doc_url: https://modin.readthedocs.io/
  dev_url: https://github.com/modin-project/modin

extra:
  recipe-maintainers:
    - devin-petersohn
    - h-vetinari
