{% set name = "modin" %}
{% set version = "0.8.0" %}

package:
  name: modin
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82418185c3340f54ab971113b86f10470ede20c9d81e256fd10b4828ae303a60

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pandas ==1.0.5
    - dask >=2.1.0
    - distributed >=2.3.2

test:
  commands:
    - python run_test.py

about:
  home: https://github.com/modin-project/modin
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Speed up your Pandas workflows by changing a single line of code
  doc_url: https://modin.readthedocs.io/
  dev_url: https://github.com/modin-project/modin

extra:
  recipe-maintainers:
    - devin-petersohn
    - h-vetinari
