{% set name = "modin" %}
{% set version = "0.8.3" %}

package:
  name: modin
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1be4b6c9b19d8e65889e5093c9479a3e519d29b8a8f9c48c44c40f81ea9bbfa2

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  # noarch disabled because the recipe now has selector for Ray, see below
  # noarch: python
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pandas ==1.1.4
    - dask >=2.1.0
    - distributed >=2.3.2
    # there is no Ray in conda-forge for MacOS yet, see https://github.com/conda-forge/ray-packages-feedstock/issues/2
    - ray-core >=1.0  # [win or linux]

test:
  commands:
    - python run_test.py

about:
  home: https://github.com/modin-project/modin
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Speed up your Pandas workflows by changing a single line of code
  doc_url: https://modin.readthedocs.io/
  dev_url: https://github.com/modin-project/modin

extra:
  recipe-maintainers:
    - devin-petersohn
    - h-vetinari
