{% set version = "0.18.0" %}

package:
  name: modin-packages
  version: {{ version }}

source:
  url: https://github.com/modin-project/modin/archive/refs/tags/{{ version }}.tar.gz
  sha256: 79eee6da579729fb00476e7ed7f32224a4242f779c9dfb49ed409d73f52cfe52
  patches:
    # Remove all requirements from setup.py - they should be handled here.
    # The point is to create a "patch failed" conflict when dependencies change
    # in upstream so this doesn't go unnoticed.
    - patches/0002-Remove-dependencies-from-setup.py.patch

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - patch     # [unix]
    - m2-patch  # [win]

# the outputs map the modin options on PyPI (see upstream definition
# https://github.com/modin-project/modin/blob/0.10.1/setup.py#L40-L45)
# from "modin[<option>]" to "modin-<option>" as a conda-forge package
outputs:
  - name: modin-core
    build:
      skip: true  # [py<38]
      script: python -m pip install . --no-deps --ignore-installed -vv
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - python
        - packaging
        - pandas ==1.5.2
        - numpy >=1.18.5
        - fsspec
        - psutil
    test:
      imports:
        - modin
        - modin.pandas
      commands:
        - pip check
      requires:
        - pip

  - name: modin_core
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('modin-core', exact=True) }}
    test:
      imports:
        - modin

  - name: modin-dask
    build:
      skip: true  # [py<38]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - dask >=2.22.0
        - distributed >=2.22.0
    test:
      imports:
        - modin
        - modin.pandas
      commands:
        - python -c "import modin.pandas as pd, modin.config as cfg; cfg.Engine.put('Dask'); df = pd.DataFrame([])"

  # compatibility with packagename before split into options
  - name: modin
    build:
      skip: true  # [py<38]
    requirements:
      host:
        - python
      run:
        - python
        # modin needs at least one engine; use dask as it is more light-weight than ray
        - {{ pin_subpackage('modin-dask', exact=True) }}
    test:
      imports:
        - modin
        - modin.pandas

  - name: modin-ray
    build:
      # There is no Ray in conda-forge for MacOS yet, see conda-forge/ray-packages-feedstock#2.
      skip: true  # [py<38]      
      # skipping architectures that do not yet have bazel, ray-core, and ray-default, so only build for linux64 & win64
      skip: true  # [osx]
      skip: true  # [not (x86_64 or win)]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - ray-default >=1.13.0
        # https://github.com/modin-project/modin/pull/5270#issuecomment-1331172629
        # workaround for https://github.com/conda/conda/issues/11744
        - grpcio !=1.45.*,!=1.46.*
        - pyarrow
    test:
      imports:
        - modin
        - modin.pandas
      commands:
        - python -c "import modin.pandas as pd, modin.config as cfg; cfg.Engine.put('Ray'); df = pd.DataFrame([])"

  - name: modin-omnisci
    build:
      # there is no OmniSci on anything but Linux for now
      skip: true  # [not (linux and x86)]
      skip: true  # [py<38]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        # pyarrow included in pyomniscidbe 5.10.1 repacked version
        # - pyarrow =6
        - pyomniscidbe ==5.10.1
      run_constrained:
        # ------------------------------------------------------------------------
        # repack of pyarrow 6.0.1 requires preventing installation with other 
        # versions of pyarrow.
        # ------------------------------------------------------------------------
        - pyarrow ==6.0.1
    test:
      requires:
        - pytest
        - numpy
        - pandas
      imports:
        - modin
        - modin.pandas
      source_files:
        - modin/
        - examples/data/
      commands:
        - python -c "import modin.experimental.pandas as pd, modin.config as cfg; cfg.Engine.put('Native'); cfg.StorageFormat.put('OmniSci'); df = pd.DataFrame([])"
        - cd modin/experimental/core/execution/native/implementations/omnisci_on_native/test/ && pytest test_dataframe.py

  - name: modin-all
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - {{ pin_subpackage('modin-dask', exact=True) }}
        # ray does not have OSX builds yet - modin-ray and modin-omnisci are mutually exclusive because of pyarrow 6.0.1
        - {{ pin_subpackage('modin-ray', exact=True) }}             # [(x86_64 or win) or not osx]
        # Note: modin-omnisci is conda-only, its dependencies were never published on PyPI
        - {{ pin_subpackage('modin-omnisci', exact=True) }}        # [linux and x86]
    test:
      imports:
        # dummy test; actual tests are in subpackages
        - modin

about:
  home: https://github.com/modin-project/modin
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Speed up your Pandas workflows by changing a single line of code
  doc_url: https://modin.readthedocs.io/
  dev_url: https://github.com/modin-project/modin

extra:
  recipe-maintainers:
    - devin-petersohn
    - h-vetinari
    - vnlitvinov
    - maksimbo1
  feedstock-name: modin
